# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centrales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=25)),
                ('direccion', models.CharField(max_length=110)),
                ('telefono', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cif', models.CharField(blank=True, max_length=9)),
                ('nombre', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=2)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='centrales',
            name='cif_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Empresas'),
        ),
        migrations.AddField(
            model_name='centrales',
            name='codigo_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.Provincias'),
        ),
    ]
