# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centrales',
            name='id',
        ),
        migrations.RemoveField(
            model_name='empresas',
            name='id',
        ),
        migrations.RemoveField(
            model_name='provincias',
            name='id',
        ),
        migrations.AlterField(
            model_name='centrales',
            name='nombre',
            field=models.CharField(blank=True, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='cif',
            field=models.CharField(blank=True, max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provincias',
            name='codigo',
            field=models.CharField(blank=True, max_length=2, primary_key=True, serialize=False),
        ),
    ]
